# Generated by Django 5.1.2 on 2025-01-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='')),
                ('Quantity', models.IntegerField()),
                ('Unitprice', models.IntegerField()),
                ('Brand', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=10000)),
            ],
        ),
    ]
