# Generated by Django 5.1.2 on 2025-01-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_producttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productid', models.IntegerField()),
                ('Productname', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('Userid', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Firstname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productid', models.IntegerField()),
                ('Productname', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('Userid', models.CharField(max_length=100)),
            ],
        ),
    ]
